-- Setup global configs
require 'globals.options'
require 'globals.keymaps'

-- Load plugins
require 'plugins'
require 'plugins.tokyonight'
require 'plugins.nvim-tree'
require 'plugins.lualine'
require 'plugins.bufferline'
require 'plugins.toggleterm'
require 'plugins.telescope'
require 'plugins.which-key'
require 'plugins.nvim-lspconfig'
require 'plugins.lspsaga'
require 'plugins.cmp'
require 'plugins.nvim-treesitter'
require 'plugins.nvim-autopairs'
require 'plugins.prettier'
require 'plugins.null-ls'
require 'plugins.git'
require 'plugins.mason'
